version: 1
devices:
  Living Room Sensor:
    - platform: binary_sensor
      name: Living Room Sensor
      initial_value: "off"
      class: motion
  Back Door Sensor:
    - platform: binary_sensor
      name: Back Door Sensor
      initial_value: "off"
      class: door
  Virtual Switch 1:
    - platform: switch
      name: Virtual Switch 1
  Virtual Switch 2:
    - platform: switch
      name: Virtual Switch 2
  Virtual Switch 3:
    - platform: switch
      name: Virtual Switch 3
  Virtual Switch 4:
    - platform: switch
      name: Virtual Switch 4
  Virtual Switch 5:
    - platform: switch
      name: Virtual Switch 5
  Virtual Switch 6:
    - platform: switch
      name: Virtual Switch 6
  Virtual Switch 7:
    - platform: switch
      name: Virtual Switch 7
  Virtual Switch 8:
    - platform: switch
      name: Virtual Switch 8
  Virtual Switch 9:
    - platform: switch
      name: Virtual Switch 9
  Virtual Switch 10:
    - platform: switch
      name: Virtual Switch 10
  Virtual Switch 11:
    - platform: switch
      name: Virtual Switch 11
  Virtual Switch 12:
    - platform: switch
      name: Virtual Switch 12
  Virtual Switch 13:
    - platform: switch
      name: Virtual Switch 13
  Virtual Switch 14:
    - platform: switch
      name: Virtual Switch 14
  Virtual Switch 15:
    - platform: switch
      name: Virtual Switch 15
  Virtual Switch 16:
    - platform: switch
      name: Virtual Switch 16
  Virtual Switch 17:
    - platform: switch
      name: Virtual Switch 17
  Virtual Lock:
    - platform: lock
      name: Front Door Lock
      initial_value: locked
      locking_time: 5
      jamming_test: 5
  Virtual Fan:
    - platform: fan
      speed: true
      speed_count: 5
      direction: true
      oscillate: true
  Virtual Cover:
    - platform: cover
      initial_value: "closed"
